apiVersion: apps/v1
kind: Deployment
metadata:
    name: template-depl
    namespace: default
spec:
    replicas: 1
    selector:
        matchLabels:
            app: template
    template:
        metadata:
            labels:
                app: template
        spec:
            containers:
                - name: template
                  image: template
---
apiVersion: v1
kind: Service
metadata:
    name: template-srv
spec:
    selector:
        app: template
    ports:
        - name:
          protocol: TCP
          port: 3000
          targetPort: 3000
