apiVersion: apps/v1
kind: Deployment
metadata:
    name: template-mysql-depl
    namespace: default
spec:
    replicas: 1
    selector:
        matchLabels:
            app: template-mysql
    template:
        metadata:
            labels:
                app: template-mysql
        spec:
            containers:
                - name: template-mysql
                  image: mysql
                  restart: always
                  command: --default-authentication-plugin=mysql_native_password
                  environment:
                      MYSQL_ROOT_PASSWORD: password
                      MYSQL_DATABASE: test

---
apiVersion: v1
kind: Service
metadata:
    name: template-mysql-srv
spec:
    selector:
        app: template-mysql
    ports:
        - name: template-mysql-port
          protocol: TCP
          port: 3306
          targetPort: 3306
